<?php 
    require_once("Config/config.php");
    require_once("Controllers/inicioSesionController.php");

    if(isset($_SESSION['nUsuario']) && isset($_SESSION["clave"])){
        if($_SESSION["tipoUsuario"] == "docente"){
            require_once("Controllers/indexController.php");
            if(isset($_REQUEST["a"])){
                if(method_exists('indexController',$_REQUEST["a"])){
                    indexController::{$_REQUEST['a']}();
                }
            }
            require_once("Controllers/materiaController.php");
            if(isset($_REQUEST["ma"])){
                if(method_exists('materiaController',$_REQUEST["ma"])){
                    materiaController::{$_REQUEST['ma']}();
                }
            }
            require_once("Controllers/inscripcionController.php");
            if(isset($_REQUEST["i"])){
                if(method_exists('inscripcionController',$_REQUEST["i"])){
                    inscripcionController::{$_REQUEST['i']}();
                }
            }
            require_once("Controllers/notasController.php");
            if(isset($_REQUEST["n"])){
                if(method_exists('notasController',$_REQUEST["n"])){
                    notasController::{$_REQUEST['n']}();
                }
            }
        }
        if($_SESSION["tipoUsuario"] == "alumno"){
            require_once("Controllers/inicioAluController.php");
            if(isset($_REQUEST["in"])){
                if(method_exists('inicioAluController',$_REQUEST["in"])){
                    inicioAluController::{$_REQUEST['in']}();
                }
            }
            require_once("Controllers/materiaAluController.php");
            if(isset($_REQUEST["mat"])){
                if(method_exists('materiaAluController',$_REQUEST["mat"])){
                    materiaAluController::{$_REQUEST['mat']}();
                }
            }
            require_once("Controllers/inscribirAluController.php");
            if(isset($_REQUEST["ins"])){
                if(method_exists('inscribirAluController',$_REQUEST["ins"])){
                    inscribirAluController::{$_REQUEST['ins']}();
                }
            }
            require_once("Controllers/notaAluController.php");
            if(isset($_REQUEST["vn"])){
                if(method_exists('notaAluController',$_REQUEST["vn"])){
                    notaAluController::{$_REQUEST['vn']}();
                }
            }
        }
    }
    else{
        if(isset($_REQUEST["m"])){
            if(method_exists('inicioSesionController',$_REQUEST["m"])){
                inicioSesionController::{$_REQUEST['m']}();
            }
        }
        else{
            inicioSesionController::index();
        }     
    }
 ?>